language: ruby
sudo: false
cache: bundler
script: rake test:all
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby
  - jruby-head
  - rbx-2
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
